### ISSUE TITLE
Popover support

### ISSUE THREAD

**Issue by beretboat** [ptmt/react-native-desktop#19]
(First of all thanks for the great work.)
Any plan to support popover?

**Comment by ptmt** [comment]
You can achieve this now with the combination of using `onMouseEnter` and `onMouseLeave` events and `position:absolute' element, but certanly it could be included in the core or as a third-party plugin.

I think I could even add it to SimpleChatExample later.

**Comment by beretboat** [comment]
An example would be wonderful. Thank you.

**Comment by beretboat** [comment]
Do you mean showing a popover window at mouse enter position? But which api should I use to show a window?

**Comment by ptmt** [comment]
I was thinking about usual `<View />`. Windows (NSWindow) isn't supported yet.

**Comment by ptmt** [comment]
Do you still have a such problem? 
With 0.4.0 release you will get tooltip support for native `<Button />` I will add it to all other controls.

**Comment by beretboat** [comment]
Sorry, how is tooltip relative to this? I meant thing like NSPopover. But I'm Ok to close this because I saw #21. Popover is just a way to show a window.

**Comment by ptmt** [comment]
Oh, I see. I tried NSPopover for menubar app, by the way, looked like this:  ![](https://cloud.githubusercontent.com/assets/1004115/13004952/b1a5e96c-d18f-11e5-978e-ab9227185389.png). It requires a native code, though, right now.
About #21 you mean you need a Microsoft Windows support, so you are not able to use RND right now?

**Comment by beretboat** [comment]
Sorry again. I mistake, I meant #40 , not #21 .

**Comment by ptmt** [comment]
I was able to solve (sorta) this problem temporary, but couldn't decide which approach is better. Could you describe your use case there?

**Comment by beretboat** [comment]
Sorry for the delay.
My use case is something like this:
![sc](https://camo.githubusercontent.com/4076aaab3776aad5883d3e2dd471252ad47186fe/68747470733a2f2f7261772e6769746875622e636f6d2f6164616d68617274666f72642f415348446174655069636b65722f6d61737465722f73637265656e73686f742e706e67)

**Comment by ptmt** [comment]
Ok, I will investigate into that, it certanly should be a lightweight solution. BTW, thanks for your contributions: https://github.com/ptmt/react-native-desktop/releases/tag/v0.4.0

**Comment by beretboat** [comment]
Congrats on the release, and again thanks for the great work. :-)
