### ISSUE TITLE
Touchable* does not support Image?

### ISSUE THREAD

**Issue by beretboat** [ptmt/react-native-desktop#26]
Wrapping `Text` in `Touchable*` works fine. But for `Image`, `onPress` callback will not be invoked and there's no highlighting effect.

**Comment by ptmt** [comment]
Thanks for report! Fixed and added the example with `<TouchableHighlight><Image /></TouchableHighlight>` to UIExplorer. (Also added the example of a simulation of Hover effect via `onMouseEnter/onMouseLeave`.)

**Comment by ptmt** [comment]
Published as `@0.2.2`.

**Comment by beretboat** [comment]
Thanks for the quick fix!
