### ISSUE TITLE
stuck on welcome screen ?

### ISSUE THREAD

**Issue by mydearxym** [ptmt/react-native-desktop#27]
love your work !

but i download the latest repo and build with XCode (Version 7.1 (7B91b)) 
then the project stuck like this : 
![image](https://cloud.githubusercontent.com/assets/6184465/12220641/04be0b48-b7b4-11e5-831d-c2d7f90fa963.png)

so, how to run this project ?

**Comment by ptmt** [comment]
That's all, you're already running it correctly :) It's a empty template.
Maybe you have tried React Native, it's the same experience. See
Index.osx.js.

**Comment by mydearxym** [comment]
@ptmt   thanks for reply , i understand.
