### ISSUE TITLE
Fatal error in -[RCTBatchedBridge loadSource:] when loading from .jsbundle

### ISSUE THREAD

**Issue by beretboat** [ptmt/react-native-desktop#28]
I generate the bundle with command 
`curl 'http://localhost:8081/index.osx.bundle?platform=osx&dev=false&minify=true' -o main.jsbundle`

The error message in Xcode console is:
"It looks like the implementation of __DEV__ has changed. Update -[RCTBatchedBridge loadSource:]."

Similar error has been issued in [react-native](https://github.com/facebook/react-native/issues/3782) and resolved with [500ffa9](https://github.com/facebook/react-native/commit/500ffa9b763d03e759e9b2897da7f4f7904934cf). I tried the fix, it works for react-native-desktop too. 

The thing is, I don't know how to sync or cherry pick changes from facebook/react-native. Suggestions?

**Comment by ptmt** [comment]
Thanks. Yeah, it has many of RN bugs, I will merge it with RN upstream (did it a few times already) once HotReload will finally get done.

**Comment by ptmt** [comment]
Did it really critical for you or you can wait for a week?
By the way there is no need to use curl, you can use `react-native-desktop bundle` cli or let XCode package bundle by itself with a build phase shell hook.

**Comment by beretboat** [comment]
Good to know. Thank you. 
Before merging I will apply the fix locally. I know there's `react-native-desktop bundle`, but I'm not sure if it fully support OS X, because the `--platform` option in command help says it only accept "ios" or "android". 
BTW this "HotReload" you mentioned, did you mean [gaearon/react-hot-loader](https://github.com/gaearon/react-hot-loader)?

**Comment by ptmt** [comment]
@bereboat, it should be fixed now in 0.3.7). Yes, I mean react-hot-loader, which partially implemented now in react-native and therefore react-native-desktop.

**Comment by beretboat** [comment]
Just tested in latest build. Yes it's fixed, thank you.
