### ISSUE TITLE
can't run react-native-desktop init <projectname>

### ISSUE THREAD

**Issue by danzalot** [ptmt/react-native-desktop#36]
Good day,

I'm new to node, npm and react-native, so sorry if this is dumb..

when I try...
react-native-desktop init MyProject

I get...
Looks like you installed react-native globally, maybe you meant react-native-cli?
To fix the issue, run:
npm uninstall -g react-native
npm install -g react-native-cli

I installed via
npm install git+https...... -g

Thanks

**Comment by ptmt** [comment]
Please try to install **cli** module globally `npm run react-native-desktop-cli -g`.

**Comment by danzalot** [comment]
No idea what that means..

I'm getting this.. 

Thanks again

`$ npm run react-native-desktop-cli -g
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "react-native-desktop-cli" "-g"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12

npm ERR! missing script: react-native-desktop-cli
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/XXXXX/devt/reactnative/src/react-native-desktop/react-native-desktop-cli/npm-debug.log

**Comment by ptmt** [comment]
@danzalot Sorry, my bad. I mean `npm run install react-native-desktop-cli -g` of course.

**Comment by ptmt** [comment]
@danzalot did you manage to run a project?

**Comment by danzalot** [comment]
No luck. 
I just get this.

npm ERR! missing script: install

is install supposed to be a separate js file or a target within one?
I guess what i'm asking is..
where do I run that command?

What I've tried..
uninstalled npm from homebrew
installed node LTS pkg installer from nodes.org
succesfully installed react-native(I can successfully generate react-native IOS projects)
run npm install react-native-desktop

**Comment by ptmt** [comment]
@danzalot `npm install react-native-desktop-cli -g`. See https://facebook.github.io/react-native/docs/getting-started.html#content for detailed manual, just add `-desktop` to `react-native` part everywhere.

**Comment by danzalot** [comment]
$ npm install react-native-desktop-cli -g
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-native-desktop-cli" "-g"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! path /usr/local/lib/node_modules/react-native-desktop-cli/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/react-native-desktop-cli/index.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/npm-debug.log

**Comment by ptmt** [comment]
@danzalot, please try again, I pushed new version to npm.

**Comment by danzalot** [comment]
Works now, thanks.

I guess some files were missing?..

$react-native-desktop init MyProj
This will walk you through creating a new React Native project in /Users/XXXX/devt/reactnative/desktop/MyProj
Installing react-native-desktop package from npm...
Setting up new React Native Desktop app in /Users/XXXX/devt/reactnative/desktop/MyProj
To run your app on OSX:
   Open /Users/XXXX/devt/reactnative/desktop/MyProj/osx/MyProj.xcodeproj in Xcode
   Hit Run button

**Comment by ptmt** [comment]
Yeah, the last npm version was broken, thank you.

**Comment by fraserxu** [comment]
The new version seems work for me now. Was not working at previous version. Thanks for the fix @ptmt
