### ISSUE TITLE
Layout become messy after alternate adding/removing views

### ISSUE THREAD

**Issue by beretboat** [ptmt/react-native-desktop#41]
I created [a sample app](https://github.com/beretboat/RNDLayoutIssue) for the bug. The page also contains information like screenshots.
Any idea?

**Comment by ptmt** [comment]
Yeah, I've got that recently. Thanks for reproducing! It seems that it wasn't the issue on 0.2.x, though. 
This is a major bug along with that border/shadow problem, so I will research on that.

**Comment by beretboat** [comment]
Thank you!
I tried 0.2.1 and 0.3.1*, both versions reproduced.
