### ISSUE TITLE
Problem of window resize

### ISSUE THREAD

**Issue by jhen0409** [ptmt/react-native-desktop#47]
Just use init project, it will have the following problem:

![demo2](https://cloud.githubusercontent.com/assets/3001525/13894225/9ebf2dc2-eda0-11e5-8733-302483669510.gif)

**Comment by ptmt** [comment]
Can't reproduce that on 0.5.0. Need more details.

**Comment by beretboat** [comment]
I can reproduce the exact problem with a project by `react-native-desktop init`.

I think it might has something to do with `NSFullSizeContentViewWindowMask` `styleMask` of the window(Code is in AppDelegate.m, `-[AppDelegate init]`):
* With `NSFullSizeContentViewWindowMask` (default code), I see the problem @jhen0409 reported.
* Remove `NSFullSizeContentViewWindowMask`, the `RCTRootContentView` will not go with `RCTRootView` when window resized:
<img width="937" alt="screen shot 2016-03-19 at 9 39 58 pm" src="https://cloud.githubusercontent.com/assets/4593681/13898898/5189170e-ee1b-11e5-85fd-448dcc23b0de.png">

**Comment by ptmt** [comment]
> But I can only reproduce this on a Macbook Pro(15'', Retina, Mid 2012), not iMac 5k.

Thanks, this is useful! Can't reproduce on 0.5.0 `init` with MBP 15'' Retina, OS X 10.11.3 (resizing smoothly). Will try on 10.10 today. So it clearly depends on an environment, sure, we could use default mask window, but I'd like to reproduce a problem first.

**Comment by beretboat** [comment]
With or without NSFullSizeContentViewWindowMask, the difference is NSFullSizeContentViewWindowMask will turn on layer backing.
And BTW I'm on 10.11.3 too.

**Comment by ptmt** [comment]
Reproduced on a slow 10.10 machine. I've made a workaround, but the are two bigger problems to further investigation: "slow" `layout` and the right way to handle complex layouts on resizing. But this is a different topic, I hope to get it eventually.

**Comment by beretboat** [comment]
The infinite layouting problem is gone. `RCTContentView` still not being resized as window resized when `NSFullSizeContentViewWindowMask` not opted in. A workaround is to turn on layer backing for `RCTRootView`.

**Comment by ptmt** [comment]
@bereboat what is your solution here? Would you mine to send the pull request?

**Comment by beretboat** [comment]
I don't have a 'precise' fix. There're several places in the code that assume view has layer. So I just turned on layer backing for `RCTRootView`. 
Do you think the solution is OK? If yes I could send a PR.

**Comment by ptmt** [comment]
I have at least few places with such solutions. You could add something like `// TODO:` mark. If in the future we get more resources to work on this, we could improve it. By the way, what is the best way to contact you? I have a question regarding RND.

**Comment by beretboat** [comment]
You could reach at by beretboat(at)gmail.com
