### ISSUE TITLE
SimpleChatClient problem?

### ISSUE THREAD

**Issue by JasonLiuOrg** [ptmt/react-native-desktop#50]
I want to use react-native-desktop to develop mac app. But I open the example of it ,there is some problem:
2016-03-30 19:20:27.268 [info][tid:com.facebook.React.JavaScript][RCTJSCProfiler.m:63] JSC profiler is not supported.
2016-03-30 19:20:27.783 [fatal][tid:main] Cannot find entry file Examples/SimpleChatClient/index.osx.js in any of the roots: ["/Users/Jincheng/Desktop/MyProject"]

**Comment by beretboat** [comment]
The steps to run the example app is the same as [react-native](https://facebook.github.io/react-native/docs/getting-started.html#content) for iOS. Have you done that?

**Comment by JasonLiuOrg** [comment]
Yes, I have done that, but the problem still exits. @beretboat

**Comment by beretboat** [comment]
'JSC profiler is not supported.' is ignorable. The fatal one is 'Cannot find entry file...'. 
I don't know how it happen and I can't reproduce it. It looks like a environment issue. Maybe you could try  cleaning up, updating your node and other dependencies, and then starting over.

**Comment by ptmt** [comment]
SimpleChatClient has its own dependencies so you need to install them:
```
cd Examples/SimpleChatClient
npm install
```

I've also updated the example to resolve some bugs.
