### ISSUE TITLE
Merge back to official React Native repo

### ISSUE THREAD

**Issue by quanglam2807** [ptmt/react-native-desktop#62]
Is there any plan to merge this project the official React Native project? It would be much easier for development.

**Comment by ptmt** [comment]
I would love to. But it requires a lot of effort, especially from react-native core maintainers. It should be proven as a high quality fork, be in high demand by a community, and backed by some serious company (such Microsoft). So, my answer is **very unlikely** for a next 6-10 months. Let's see that would be later.
