### ISSUE TITLE
What are the main differences between this fork and react-native?

### ISSUE THREAD

**Issue by geuis** [ptmt/react-native-desktop#67]
question in title

**Comment by ptmt** [comment]
This fork adds new platform as a target for React Native — Mac OS X. So instead of using Cocoa Touch it uses Cocoa (UIKit -> AppKit). Because of that, there are bunch of new APIs (like Menu) and controls (Buttons).

**Comment by ptmt** [comment]
I hope I've answered your question. Feel free to ask details, maybe I should add it to readme.
