### ISSUE TITLE
Discord chat link in README doesn’t work

### ISSUE THREAD

**Issue by kirkstrobeck** [ptmt/react-native-desktop#69]

**Comment by ptmt** [comment]
Have you got Discord account? https://discordapp.com/channels/102860784329052160/111514927801307136 should work.

**Comment by kirkstrobeck** [comment]
I do have an account. This is what shows at that URI.

![](http://f.cl.ly/items/0p2R1Y2O3X3R2S3c0i0W/Screen%20Shot%202016-04-19%20at%208.15.17%20AM.png)

**Comment by ptmt** [comment]
@kirkstrobeck Hmm, maybe this works only if you're already in Reactiflux server. Try this: http://www.reactiflux.com/ and thank you for feedback.

**Comment by kirkstrobeck** [comment]
That worked 👍
