### ISSUE TITLE
Layer backed views

### ISSUE THREAD

**Issue by mrjjwright** [ptmt/react-native-desktop#8]
Adding a backgroundColor to a view backs it with a layer.
https://github.com/ptmt/react-native-desktop/blob/master/React/Views/RCTView.m#L472

This is a natural choice.  I am worried about the performance though if there are lots of views on the screen with a background color.  Layer backed views are expensive.  Did you consider drawing a backgroundColor or would that be worse?  What about generating a backgroundColor image on the fly?  Perhaps there is no easy answer here.  NSView will naturally have much worse performance than UIViews.

http://stackoverflow.com/questions/30041190/nsview-performance-of-wantslayer
and
https://github.com/lionheart/openradar-mirror/issues/5483

**Comment by ptmt** [comment]
Yeah, you're absolutely right, it's a great topic to discuss.

CALayer mentioned even on Apple's documentation in terms of performance and I tried to not create it for *each* view. I decided to not think a lot about premature optimizations right now, and certanly will test some different approaches on the first real large desktop app which I will begin work with soon. There are so many trade-offs and questions about RND, I'm collecting tt one by one in my Notes.app. I guess I will write a blog post eventually.

**Comment by mrjjwright** [comment]
I plan to start a large desktop app with RND soon too.  I will let you know
what I find out.  I feel like everything can be worked around eventually.
The UXKit headers on the Apple Photos app proves that you can do great
things and there are a number of highly performing Mac apps.   I think we
can make this work, it will just require decisions for sure.   Thanks for
starting this amazing project.
