### ISSUE TITLE
Adding a react native based npm module

### ISSUE THREAD

**Issue by nunobbras** [ptmt/react-native-desktop#87]
When adding react native based npm module, it would be nice to have something as the webpack alias:

```
  resolve: {
    alias: {
      'react-native': 'react-native-desktop'
    }
```

Is there any nice strategy to solve this, besides duplicating packages, which is killing my project.

**Comment by ptmt** [comment]
Are you using only react-native-desktop? Have you tried to create a stub `react-native` module which only purpose is `module.exports = require('react-native-desktop')`?

**Comment by nunobbras** [comment]
No, I'll try that and let you know.
Thanks

**Comment by ptmt** [comment]
What's your status on this? What 3rd party libraries are you using?

**Comment by nunobbras** [comment]
No time to feedback yet, but this is not forgotten. I'll get back ASAP.

**Comment by nunobbras** [comment]
Yep this works, thanks for your help. Do you know a way to insert this stub in a different place than the node_modules folder and still be recognized by other modules? This can be a problem when reinstalling the modules. 
Just a final thought: if react-native is imported instead of RND in all places and this stub is used, every react-native module "compatible" with RND can work instantly. The developer is just using "the same" RN interface for desktop;

**Comment by ptmt** [comment]
Added extraNodeModules in the latest version `0.9.0-rc1` resolving `react-native` as `react-native-desktop`.
