### ISSUE TITLE
Modal Component: Native component for "RCTModalHostView" does not exist

### ISSUE THREAD

**Issue by nunobbras** [ptmt/react-native-desktop#89]
Hi, it looks the native modal component is not done yet. Is it something planned to be developed?

**Comment by ptmt** [comment]
Eventually, yes it is. But there are also huge TODO-list of other features. Do you have a real use case for it, could you describe?

**Comment by ptmt** [comment]
Fixed in https://github.com/ptmt/react-native-desktop/commit/a1ba40e00b06e0720abcd323b2e42dcf830c2ab5

Please, check it out. It's a bit different from mobile implementation, though.

**Comment by jhen0409** [comment]
@ptmt it [looks](https://www.npmjs.com/package/react-native-desktop) v0.8.7 not published yet.

**Comment by ptmt** [comment]
Published now.
