### ISSUE TITLE
NSGestureRecoginzer mouseDown sent twice with NSTextField in focus

### ISSUE THREAD

**Issue by mrjjwright** [ptmt/react-native-desktop#9]
In Google Inbox example the user has to paste the code with right click because the menu isn't hooked up.   That is an easy fix. After this the NSTextField is the first responder.

However when I click somewhere else in the window, on any other view, I get the exact same NSMouseDown event twice in `RCTTouchHandler`.  This causes it to throw an error because the `The Touch is already recorded`.   It has already seen the event.   I am on El Capitan.

I am trying to figure out why the same mouseDown event is sent twice to the gesture recognizer in these cases.  I was able to workaround it by checking for the same event and ignoring it.

<img width="472" alt="screen shot 2015-10-22 at 11 03 47 am" src="https://cloud.githubusercontent.com/assets/4343/10672426/5949b946-78ad-11e5-85a1-e49283692078.png">

**Comment by ptmt** [comment]
I got the same error a while ago, and added some temporary workaround: https://github.com/ptmt/react-native-desktop/blob/master/React/Base/RCTTouchHandler.m#L96. Anyway, mouse events is bad and incomplete right now, need to invest a more time to RCTTouchHandler to fix a few major problems. @mrjjwright  could you reach me out on muakacho at gmail.com, I would love to know what kind of apps you are going to make with RND?

**Comment by ptmt** [comment]
Need to create a reproducible scenario. It seems that the exact problem is fixed
