### ISSUE TITLE
Local server `isChromeConnected()` always return false

### ISSUE THREAD

**Issue by jhen0409** [ptmt/react-native-desktop#92]
It will not cause much of problems in debugger-ui page, because Chrome will keep the same tab, but I change to open [react-native-debugger](https://github.com/jhen0409/react-native-debugger), the local server will still try to open debugger-ui page.

**Comment by ptmt** [comment]
Thanks for report, will fix that! RN debugger is great!

**Comment by jhen0409** [comment]
Looks [local server](https://github.com/ptmt/react-native-desktop/tree/master/local-cli/server) not fully sync code, maybe related this issue? (e.g. [this commit](https://github.com/facebook/react-native/commit/64d56f34b779de94f251f4b443463cbfe790912d))

**Comment by ptmt** [comment]
@jhen0409 thanks for pointing out. Can you check your setup with the latest master commit?

**Comment by jhen0409** [comment]
@ptmt It works! thanks! :)
