### ISSUE TITLE
How to keep all representations when loading a image via <Image source={{uri:'...'}}/>?

### ISSUE THREAD

**Issue by beretboat** [ptmt/react-native-desktop#94]
When loading a **local** image with multiple representations(an .icns icon, for example) via `<Image source={{uri:'...'}} />`, only the first representation will be kept, all other representations will be abandoned. Is there a good solution to avoid that? I looked into the code a little bit but not sure how to do that without breaking current image decoding mechanism.

PS: I know using `<Image source={require('...')}  />` fashion will keep all representations, but I can't use this because I don't have image paths until runtime and `require('...')` needs a static string.

**Comment by ptmt** [comment]
Sorry for not answering. Image getting complicated these days, indeed. I remember that I even wrote a part of `<Image /`> a year ago in RN for iOS but now to be able to answer you I need a bit of spare time to dig into images.

**Comment by beretboat** [comment]
BTW, in case you forgot, the code I mentioned that only taking the first representation of the image is at RCTImageUtils.m:RCTDecodeImageWithData.

**Comment by ptmt** [comment]
Could you please add this example to `Examples/UIExplorer/ImageExample.js` to demonstrate the use case? Are you talking about loading image through `file://` which loads the single file (tiff or icns) with embedded multiple images, instead of the prefix ones (`@2x`)?

**Comment by beretboat** [comment]
Please see the image-representations-test I just pushed.
I'm loading an single icns(which has multiple representations embedded) image like this:
`<Image source={{uri:'/path/to/image.icns'}} />`

**Comment by ptmt** [comment]
Ok, I see now, thanks.
So I added `icns` to `assetExts` and tried `<Image source={require('./gear.icns'}} />` and it also loaded only the first representation. Am I missing something? 
![image](https://cloud.githubusercontent.com/assets/1004115/16035341/5a64a792-321f-11e6-9977-f780a5908726.png)


The possible way is to implement a custom decoder which implements `RCTImageDataDecoder`, but I'm not sure. Is React Native for iOS handle this properly?

**Comment by beretboat** [comment]
You're right, `<Image source={require('./gear.icns'}} />` has the problem too. Sorry I did't try it out first. In the code path I see code like `RCTIsXCAssetURL` in RCTUtils.m and I thought assert images will be handled differently.

React Native for iOS behaves the same on this. But I think this make sense for iOS because there's no DPI changes in iOS. They mention this in the [doc](http://facebook.github.io/react-native/docs/images.html), it's more like a 'feature' than a bug for React Native iOS. Plus keeping only one representation is good for performance. On the other hand, in OS X sometimes handling dynamic DPI changes is require because user is able to change DPI/resolution.

So may be it's not implementing a custom decoder, but changing current decoder. So this is not a popular requirement? If it's just me may be I should just make a local patch myself.

**Comment by ptmt** [comment]
I see, thanks for the clarification. It sounds reasonable. I'm personally using only system icons and `react-native-vector-icons` but it makes sense to have the ability to support run-time dpi changing and multiple representations for bitmaps, and I'm totally ok with getting this back to the internal implementation. My current strategy, though, to implement as many things as possible in the user space rather than RND. To see how is it going to be hard to merge later with RN and so on.

**Comment by beretboat** [comment]
Ok, thanks for your time. I'm closing this issue for now.

**Comment by ptmt** [comment]
To clarify: lets fix it if you need it for your project, just in a stand-alone branch.

**Comment by beretboat** [comment]
Got it.


Original Message
Sender:Dimanotifications@github.com
Recipient:ptmt/react-native-desktopreact-native-desktop@noreply.github.com
Cc:beretboatberetboat@gmail.com; State changestate_change@noreply.github.com
Date:Tuesday, Jun 14, 2016 18:06
Subject:Re: [ptmt/react-native-desktop] How to keep all representations whenloading a image via Image source={{uri:'...'}}/? (#94)


To clarify: lets fix it if you need it for your project, just in a stand-alone branch.
