### ISSUE TITLE
How to join #react-native-desktop channel

### ISSUE THREAD

**Issue by nabeards** [ptmt/react-native-desktop#95]
Can you tell me how to join the #react-native-desktop channel? Is that on IRC? If so, which server?

Thanks!
nabeards

**Comment by ptmt** [comment]
http://www.reactiflux.com/. But a channel has been deleted due to inactivity. See `#react-native-platforms`. (I'll change the Readme.md)

**Comment by nabeards** [comment]
Awesome, thanks!
