### ISSUE TITLE
Unable to run example project

### ISSUE THREAD

**Issue by matto1990** [ptmt/react-native-desktop#97]
I'm having issues getting the basic generated sample to run. I have tried `react-native-desktop` before and got it working right away, but today I'm having issues.

I have run:

```
brew install watchman
npm install -g react-native-desktop-cli
react-native-desktop init ExampleProject
cd ExampleProject
npm start
```

I then open the XCode project and run the app. It builds fine, but when getting the Javascript it errors with:

```
2016-07-14 23:07:01.460 [fatal][tid:main] Unable to resolve module react-native/lib/InitializeJavaScriptAppEngine from <PROJECT_PATH>/node_modules/react/lib/ReactNativeDefaultInjection.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/react-native/lib/InitializeJavaScriptAppEngine and its parent directories

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
```

I have tried all the options it gives, but it seems the error is coming from line 17 of `react/lib/NativeMethodsMixin.js` where the `react` module is attempting to bridge into `react-native` instead of `react-native-desktop`. I have tried the solution from #87 where I create a dummy package called `react-native` which just exports `react-native-desktop`, however, this does not seem to work.

Any ideas what the solution might be?

**Comment by ptmt** [comment]
Oops. React has added the direct dependency for `react-native`. Let me see that I can do about it.

**Comment by matto1990** [comment]
Thanks! Do you know if there's a combination of versions of `react` and `react-native-desktop` which I can use in the meantime. I tried looking in the `react` source code for when they made the change, but I can't actually see any of the source code in their repo. It looks like they have a really strange build system structure which changes where all the code lives...

**Comment by ptmt** [comment]
You could try: 

```
rm -rf node_modules/react node_modules/react-native-desktop
npm install react-native-desktop@0.8.7
```

**Comment by ptmt** [comment]
Please try again to re-create a project or directly specify 0.9.0-rc1.

**Comment by matto1990** [comment]
Thanks! That works brilliantly!
